/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class smartreadjava */

#ifndef _Included_smartreadjava
#define _Included_smartreadjava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     smartreadjava
 * Method:    SmartRead_InitialAuth
 * Signature: (JJJJLjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1InitialAuth
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jstring, jstring, jstring);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_Close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1Close
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_Speak
 * Signature: (Ljava/lang/String;Ljava/lang/String;IIIIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1Speak
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jint, jint, jint, jint, jstring);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_Stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1Stop
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_SetDialog
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1SetDialog
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_SpeakToWave
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;IIIIIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1SpeakToWave
  (JNIEnv *, jobject, jstring, jstring, jstring, jint, jint, jint, jint, jint, jint, jstring);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_GetLocationInfo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1GetLocationInfo
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_SetVolume
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1SetVolume
  (JNIEnv *, jobject, jint);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_GetVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1GetVolume
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_SetSpeed
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1SetSpeed
  (JNIEnv *, jobject, jint);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_GetSpeed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1GetSpeed
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_PauseORContinue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1PauseORContinue
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_GetVoiceDeviceNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1GetVoiceDeviceNum
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_GetErrCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1GetErrCode
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_GetErrMsg
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_smartreadjava_SmartRead_1GetErrMsg
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_SetParameter
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1SetParameter
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_SetMode
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1SetMode
  (JNIEnv *, jobject, jint);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_QueueNext
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1QueueNext
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_QueueStatistics
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1QueueStatistics
  (JNIEnv *, jobject, jint);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_HideMessageBox
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_smartreadjava_SmartRead_1HideMessageBox
  (JNIEnv *, jobject);

/*
 * Class:     smartreadjava
 * Method:    SmartRead_Version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_smartreadjava_SmartRead_1Version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
